name: OPA Policy Check

on:
  pull_request:

jobs:
  opa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan.binary \
             -var="aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" \
             -var="aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Convert Plan to JSON
        run: terraform show -json tfplan.binary > tfplan.json

      - name: Run OPA Policy Check
        run: |
          result=$(opa eval --format raw --data policy/bucket.rego --input tfplan.json "data.terraform.demo.allow")
          echo "OPA result: $result"
          if [ "$result" != "true" ]; then
            echo "OPA denied. Reasons:"
            opa eval --format pretty --data policy/bucket.rego --input tfplan.json "data.terraform.demo.deny"
            exit 1
          fi
